AWS:
  S3:
    BUCKET: 'smartgridgurgaon'
    BUCKET_URL: '//s3-ap-southeast-1.amazonaws.com/smartgridgurgaon/'
    ACCESS_KEY_ID: <%= ENV['AWS_ACCES_KEY_ID'] %>
    SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    REGION: 'ap-southeast-1'
ADMIN:
  USER_NAME: <%= ENV['ADMIN_USER_NAME'] %>
  PASSWORD: <%= ENV['ADMIN_PASSWORD'] %>